config/routes.rb
FoodApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:new, :create]
  resources :console
  resources :contacts, only: [:new, :create]

  root 'static_pages#home'
  match '/about',      to: 'static_pages#about',    via: 'get'
  match '/workshop',   to: 'static_pages#workshop', via: 'get'
  match '/signup',     to: 'users#new',             via: 'get'
  match '/signin',     to: 'sessions#new',          via: 'get'
  match '/signout',    to: 'sessions#destroy',      via: 'delete'
end

app/models/ayurveda.rb
class Ayurveda < ActiveRecord::Base
  has_many :users
  validate :name, presnece: true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone
  attribute :topic
  attribute :message
  attribute :nickname,  :captcha  => true
  
  def headers
    {
      :subject => "Freshly Balanced Web Inquiry",
      :to => "deborah@freshlybalanced.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  default_scope -> { order('created_at DESC') }

  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true

  self.per_page = 4
end

app/models/studio.rb
class Studio < ActiveRecord::Base
  has_many :users
  validates :name, presence: true
  accepts_nested_attributes_for :users
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  belongs_to :studio
  belongs_to :ayurveda
  has_many :posts

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  					               uniqueness: { case_sensitive: false }
  validates :studio_id, presence: true
  validates :ayurveda_id, presence: true

  validates :aliment, allow_nil: true, allow_blank: true, length: { maximum: 1000 }
  validates :allergy, allow_nil: true, allow_blank: true, length: { maximum: 1000 }
  validates :phone, numericality: true, length: { in: 10..15 }, 
                           allow_nil: true, allow_blank: true
  
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/console_controller.rb
class ConsoleController < ApplicationController
  before_action :admin_user, only: [:show]

  def new
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  	@contact = Contact.new
  end

  def create
  	@contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash[:success] = 'Thank you for contacting Freashly Balanced.  We will respond to your message shortly.'
      redirect_to root_url
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user
  before_action :admin_user
  
  def new
    @post = Post.new
  end

  def create
  	@post = current_user.posts.build(post_params)
  	if @post.save
  	  flash[:success] = "Post created!"
  	  redirect_to root_url
  	else
      render new_post_path
  	end
  end

  private

    def post_params
      params.require(:post).permit(:title, :content)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@user = User.find_by(params[:admin])
  	@posts = Post.paginate(page: params[:page])
  end

  def about
  end

  def workshop
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:index, :destroy, :admin]

  def index
    @users = User.paginate(page: params[:page])
  end
  
  def new
  	@user = User.new
  end

  def show
    @user = User.find(params[:id])
    @post = current_user.posts.build if signed_in?
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Food App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :studio_id,
      							               :ayurveda_id, :aliment, :allergy, :birthday,
                                   :location, :phone, :password,
                                   :password_confirmation)
    end

    # Before filters

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end   
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.       
  def full_title(page_title)                          
    base_title = "Food App"  
    if page_title.empty?                              
      base_title                                      
    else
      "#{base_title} | #{page_title}"             
    end
  end 
end

app/helpers/console_helper.rb
module ConsoleHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
end

app/views/console/show.html.erb
<% provide(:title, 'Admin Console') %>
<h3>Admin Console for <%= @user.name %></h3><br>

<div class='row'>
  <%= render 'shared/admin_sidebar' %>
  <div class="span8 well">
  	Welcome to the Administative Console.  Click a link to get started.
  </div>
</div>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<% provide(:title, 'Contact') %>
<h3>We'd love to hear from you!</h3>
<div class="row">
  <div class="col-md-7 col-md-offset-1 well">
    <p>Contact us by phone at 603-361-4296.</p>
    <p>Contact us via the web:</p>
  	<%= form_for @contact, :html => { :class => 'form-horizontal' } do |f| %>
      <fieldset>
        <%= render 'shared/error_messages', object: f.object %>

        <div class="input-group">
          <span class="input-group-addon">Name</span>
          <%= f.text_field :name, :class => 'form-control', :required => true %>
        </div><br><br>

        <div class="input-group">
          <span class="input-group-addon">Email</span>
          <%= f.email_field :email, :class => 'form-control', :required => true %>
        </div><br><br>

        <div class="input-group">
          <span class="input-group-addon">Phone Number</span>
          <%= f.telephone_field(:phone, :class => 'form-control') %>
        </div><br><br>

        <div class="input-group">
          <span class="input-group-addon">Message</span>
          <%= f.text_area :message, :as => :text, :required => true, :class => 'form-control' %>
        </div><br><br>
    
        <div class= "hidden">
          <%= f.hidden_field :nickname, :hint => 'Leave this field blank!' %>
        </div>

        <div>
          </br>
          <%= f.submit "Send Message", :class=> "btn btn-info" %>
        </div>
      </fieldset>
    <% end %>   
  </div>
</div> 

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Site created by <a href="#">AJW</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home",    root_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", new_contact_path %></li>
    </ul>
  </nav> 
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Freshly Balanced", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Home",     root_path %></li>
          <li><%= link_to "About",    about_path %></li>
          <li><%= link_to "Contact",  new_contact_path %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Services <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Weekly Menu", '#' %></li>
                <li><%= link_to "Workshops", workshop_path %></li>
              </ul>
            </li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Admin Console", console_path(current_user) if current_user.admin? %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<meta name="viewpoint" content="width=device-width, initial-scale=1.0">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
  	<%= yield %>
  	<%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/posts/_post.html.erb
<div class="panel panel-success">
  <div class="panel-heading"><%= post.title %></div>
  <div class="panel-body">
  	<%= post.content %><br>
    <span class="timestamp">
      <div><br> Posted by <%= post.user.name %>, <%= time_ago_in_words(post.created_at) %> ago</div><br>
    </span>
  </div>
  
</div>

app/views/posts/new.html.erb
<% provide(:title, 'Create a Post') %>
<div class="col-md-offset-3"><h3>Create a Post</h3></div>
<div class="row">
  <%= render 'shared/admin_sidebar' %>
  <div class="col-md-8 well">
    <%= form_for @post do |f| %>
      <fieldset>
        <% render :partial => "shared/error_messages", :locals => {:object => @post} %>
  
        <div class="control-group">
          <%= f.label :title, :class => 'control-label' %>
          <%= f.text_field :title %>
        </div>

        <div class="control-group">
          <%= f.label :content, :class => 'control-label' %>
          <%= f.text_area :content, placeholder: "Compose new post..." %>
        </div>

        <div class="form-actions">
          <%= f.submit "Create Post", class: "btn btn-info" %>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/shared/_admin_sidebar.html.erb
<div class='col-md-3'>
    <%= link_to "Display Users", users_path %><br/>
    <%= link_to "Create a Post", new_post_path %><br/>
  	<a href='#'>Edit Menu Items</a><br/>
  	<a href='#'>Order History</a><br />
  	<a href='#'>This Weeks Orders</a>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="row">
  <div class="col-md-7">
    <h3>Mission Statement</h3>
    <div  class="well">
      <p>It is the mission of Freshly Balanced to creatively combine organic whole foods and spices with ancient Ayurvedic culinary principles into convenient pre-made dishes that support balancing optimum health and busy lifestyles.  My empowering and educational workshops actively gives to individuals the ability to do, feel, and believe in their own culinary skills while building a healthy, nuturing and plentiful life.</p>
    </div>
    <br>
    <div class="panel panel-success">  
      <div class="panel panel-heading">
        <h4 class="panel-title">A letter from the founder</h4> 
      </div> 
      <p class="panel-body">Hello, <br>
        My name is Deborah Mugherini and I started this venture to support and carry the message of hope and recovery to people as we each play out our own hand in this game of life.  For many many long years I struggled with eating disorders and Crohn’s disease.  Today, I recognize the deeper meaning behind my struggles as a testament of how far away I had been living my life relative to my true self.  I started my road to recovery by experimenting in the kitchen over 10 years ago with organic foods and the results have grown into a passion for creating culinary works of art.  In 2009, shortly after graduating with my MBA, I took a leap of faith and opened a specialty bake shoppe focusing on gourmet cakes and cupcakes.  This first venture lasted a few years and included both wholesale and retail distribution as well as wedding catering.  More recently, as I continue my journey towards finding inner balance, I have been led to the healing principles of Ayurveda.  With the help of Pratibha Shah at <a href="http://www.zanjabee.com/">Zanjabee Integrative Medicine</a>, I have become even more inspired to use nature and organic foods to heal my mental, physical, and spiritual well-being.  As I fulfill my purpose, I am overcome with gratitude for all the wonderful people I have met through the years.  I hope to continue to feed the souls of many more wonderful people to come.  
        <br> Namaste.
      </p>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
  <!-- Carousel  ================================================== -->
  <div id="myCarousel" class="carousel slide">
  <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="item active">
        <img src="/images/banner.jpg" class="img-responsive">
        <div class="container">
          <div class="carousel-caption">
            <h1>Live life where food is medicine & the kitchen your pharmacy</h1>
            <pthis is="" an="" example="" layout="" with="" carousel="" that="" uses="" the="" bootstrap="" 3="" styles.<="" small=""><p></p></pthis>
          </div>
        </div>
      </div>
      <div class="item">
        <img src="/images/banner1.jpg" class="img-responsive">
        <div class="container">
          <div class="carousel-caption">
            <h1>Schedule a workshop on pairing spices</h1>
            <p><%= link_to "Learn More", workshop_path, class: "btn btn-lg btn-primary" %></p>
          </div>
        </div>
      </div>
      <div class="item">
        <img src="/images/banner2.jpg" class="img-responsive">
        <div class="container">
          <div class="carousel-caption">
            <h1>vegetarian options!</h1>
            <p><%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %></p>
          </div>
        </div>
      </div>
    </div>
  <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="icon-next"></span>
    </a>  
  </div><br>
<!-- /.carousel -->
<div class="row">
  <div class="col-md-9"> 
  	<div>
      <% unless @posts.blank? %>
        <ol>
          <%= render @posts %>
        </ol>
        <%= will_paginate @posts %>
      <% end %>
  	</div>
  </div>
  <div class="col-md-3">
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-success" %>
    <div class="profile"> 
      <div><img src="/images/profilepic.jpg"></div>
      <p>Hey hey!</p>
      <p>My name is Deborah and I am on a journey towards making piece with being uncomfortable.  I started this blog to help me be brave enough to admit to how I feel and that who I really am.</p>
      <p>My posts are a timetable of me sorting through the various levels of contrast in my life's experiences, in an attempt to expose the good and bad.  This is a raw insight into my own learning processes in striving to express and allow my emotions, wounds, traumas and pains to surface healthfully and with love. With support and honesty as my allies, I seek the comfort of true acceptance of where I am today, in order to move in the direction of that which I desire. </p>
      <p>I founded Freshly Balanced as my own personal responsibility to honor my self, apply what I learn to my life, and carry the message of love and hope to others.  I welcome you to join me as my journey continues to unfold. </p>
      <img src="/images/signature.jpg">
    </div>
  </div>
</div>

app/views/static_pages/workshop.html.erb
<% provide(:title, 'Workshops') %>

<div class="row">
  <h3>Educational Cooking Workshops</h3><br>
  <div class="col-md-7 col-md-offset-1 well">
  <div class="workshops">    
    <h2>Herbs and Spices</h2>
    <p>Spices have been an integral part of civilization, serving as a preservative, flavoroid, and/or medicine.  This class is designed to empower people to expand their culinary creativity by teaching the art of how to manipulate herbs and spices to evoke flavor. </p>
    <p>Beginning with a fun and interactive taste testing game to learn about the importance of different tastes and sensations in preparing dishes.  Participants will become submersed in their own senses relative to the different herbs and spices often found in Indian cuisine as well as many Eastern and Mediterranean cultures.  Handouts will be provided to help distill the individual properties of each.  We will discuss how to use this information to create different desired tastes as well as the foundation for fixing dishes that have gone spice-array.</p>
    <p>Participants will receive a take-home spice pairing chart designed to assist them when experimenting with how to enhance and balance different flavors in their own dishes.  An exciting game of jeopardy will round out the class and reinforce all information covered.  Prizes will be awarded to the host as well as the participants who win the taste testing and jeopardy games.  The class ends with an optional live demonstration of how to properly dry roast, grind, and store spices to maximize flavor and shelf life. </p>
  </div>
  </div>
  <div class="col-md-3">
    <div class="details">
  	  <h4>Details</h4>
  	  <p>Price:<br />
  	    <ul>
  	  	  <li>$50 per person</li>
  	      <li>$60 per person with live demonstraion</li>
  	    </ul><br />
      <p>Each workshop runs for 2 hours, 2.5 hours with a live demontraion.  All live demonstrations require access to a kitchen.  The price includes all spices and herbs used during the demonstarion.</p>
      <p><b>Contact us today to set up your party! And let the fun begin! </b></p>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h3>Update your profile</h3>

<div class="row well">
  <%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
    <fieldset>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="col-md-6">
        <h2>About Me</h2>
        <div class="control-group">
          <%= f.label :birthday, :class => 'control-label' %>
          <%= f.date_field :birthday %>
        </div>

        <div class="control-group">
          <%= f.label :phone, "Phone Number", :class => 'control-label' %>
          <%= f.telephone_field(:phone) %>
        </div>

        <div class="control-group">
          <%= f.label :location, :class => 'control-label' %>
          <%= f.text_field :location, :placeholder => "Town, State" %>
        </div>

        <div class="control-group">
          <%= f.label :aliments, :class => 'control-label' %>
          <%= f.text_area :aliment %>
        </div>

        <div class="control-group">
          <%= f.label :allergies, :class => 'control-label' %>
          <%= f.text_area :allergy %>
        </div>
      </div>

      <div class="col-md-5">
        <h2>Personal Information</h2>
        <div class="control-group">
          <%= f.label :name, :class => 'control-label' %>
          <%= f.text_field :name, :class => 'text_field' %>
        </div>

        <div class="control-group">
          <%= f.label :email, :class => 'control-label' %>
          <%= f.email_field :email, :class => 'text_field' %>
        </div>

        <div class="control-group">
          <%= f.label :studio, :class => 'control-label' %>
          <%= collection_select(:user, :studio_id, Studio.all, :id, :name) %>
        </div>
      
        <div class="control-group">
          <%= f.label :ayurveda, :class => 'control-label' %>
          <%= collection_select(:user, :ayurveda_id, Ayurveda.all, :id, :name) %>
        </div>
      </div>

      <div class="col-md-7 col-md-offset-3">
        <h4>Enter your password and confirm to update your profile</h4>

        <div class="control-group">
          <%= f.label :password, :class => 'control-label' %>
          <%= f.password_field :password %>
        </div>

        <div class="control-group">
          <%= f.label :password_confirmation, "Confirmation", :class => 'control-label' %>
          <%= f.password_field :password_confirmation %>
        </div>

        <div class="form-actions">
          <%= f.submit "Save changes", class: "btn btn-info" %>
          <%= link_to 'Cancel', current_user, :class => 'btn btn-danger' %>
        </div>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<div class="col-md-offset-3"><h3>Customer List</h3></div>

<div class='row'>
  <%= render 'shared/admin_sidebar' %>
  <%= will_paginate %>
  <div class='col-md-5 well'>
    <ul class="users">
      <% @users.each do |user| %>
        <li>
          <%= link_to user.name, user %>
          <% if current_user.admin? && !current_user?(user) %>
    |       <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
          <% end %>
        </li>
      <% end %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>


<div class="row">
  <div class="col-md-6 col-md-offset-3"><h3>Sign up</h3></div>
  <div class="col-md-6 col-md-offset-3 well">
    <%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
      <fieldset>
      <%= render 'shared/error_messages', object: f.object %>

        <div class="input-group">
          <span class="input-group-addon">Name</span>
          <%= f.text_field :name, :class => 'form-control', :required => true %>
        </div><br><br>

        <div class="input-group">
          <span class="input-group-addon">Email</span>
          <%= f.email_field :email, :class => 'form-control', :required => true %>
        </div>
<br>
        <div class="control-group">
          <%= f.label :studio, "Yoga Studio", :class => 'control-label' %><br><br>
          <div class="controls">
            <%= collection_select(:user, :studio_id, Studio.all, :id, :name,
                                  prompt: "Select your Yoga Studio") %>
          </div>
        </div>
      
        <div class="control-group">
          <%= f.label :ayurveda, "Ayurveda Practioner", :class => 'control-label' %><br><br>
          <div class="controls">
            <%= collection_select(:user, :ayurveda_id, Ayurveda.all, :id, :name, 
                                  prompt: "Select your Practionier") %>
          </div>
        </div>

        <div class="input-group">
          <span class="input-group-addon">Password</span>
          <%= f.password_field :password, :class => 'form-control', :required => true %>
        </div><br><br>

        <div class="input-group">
          <span class="input-group-addon">Confirmation</span>
          <%= f.password_field :password_confirmation, :class => 'form-control', :required => true %>
        </div><br><br>

        <div class="form-actions">
          <%= f.submit "Create my account", class: "btn btn-large btn-info" %>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
  <h3><%= @user.name %></h3>
  <div class="row">
    <div class="col-md-5 well">
      <h3>Personal Information</h3>
        <b>Current email: </b><%= @user.email %><br/ >
        <b>Yoga Studio: </b><%= @user.studio.try(:name) %><br/ >
        <b>Ayurveda Practioner: </b><%= @user.ayurveda.try(:name) %><br/ >
      <h3>About Me</h3>
        <b>Aliments: </b><%= @user.aliment %><br/ >
        <b>Known allgeries: </b><%= @user.allergy %><br/ >
        <b>Birthday: </b><%= @user.birthday %><br/ >
        <b>Location: </b><%= @user.location %><br/ >
        <b>Phone number: </b><%= @user.phone %><br/ >
    </div>
    <div class="col-md-5 col-md-offset-1 well">
  	  <h3>Recent Orders</h3>
  	    A list of recently ordered menu items
    </div>  
  </div>